MySay/Models/Poll.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MySay.Models
{
  public class Poll
  {
    public int Id { get; set; }
    [Required]
    public string Description { get; set; }
    [Required]
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")] 
    public DateTime EndingOn { get; set; }
  }
}

MySay/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MySay.Controllers
{
  public class AccountController : Controller
  {
    [HttpGet]
    public ActionResult Register()
    {
      return View();
    }
  }
}

MySay/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MySay.Controllers
{
  public class HomeController : Controller
  {
    public ActionResult Index()
    {
      ViewBag.Title = "Home page";
      return View();
    }

  }
}

MySay/Controllers/PollsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MySay.DB;
using MySay.Models;

namespace MySay.Controllers
{
  public class PollsController : Controller
  {
    /*
     * What we need
     * Current Polls
     * Popular polls
     * 
     * create polls
     * invite others to join/vote and remind
     * using google contacts
     * using facebook contacts
     * using facebook/google share
     * simple polls
     * order or finding priority polls
     * 
     * Create Account
     * using facebook
     * using google
     * share poll results using FB, Google, Twitter
     * */
    public ActionResult Index()
    {
      return View(new Poll());
    }

    public readonly PollRepository repository = new PollRepository();

    [HttpGet]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Poll poll)
    {
      if (ModelState.IsValid)
      {
        repository.Create(poll);
        return RedirectToAction("Index");
      }
      else
        return View(poll);
    }

    public ActionResult GetPopularPolls()
    {
      var polls = repository.GetPolls();
      return View("ListPolls",polls);
    }

    public ActionResult GetCurrentPolls()
    {
      var polls = repository.GetPolls();
      return View(polls);
    }
  }
}

MySay/Views/Home/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<div ng-view></div>
{{1+1}}

MySay/Views/Polls/Create.cshtml
@model MySay.Models.Poll

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Poll</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EndingOn)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EndingOn)
            @Html.ValidationMessageFor(model => model.EndingOn)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

MySay/Views/Polls/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.ActionLink("Create Mine", "Create", "Polls", null, new { @class = "btn btn-default" })

<h3>Popular Polls</h3>
@{
  var repo = new MySay.DB.PollRepository();
  var popular = repo.GetPolls();
  Html.RenderPartial("ListPolls", popular);
}

<br />
<hr />
<h3>Current Polls</h3>
@{
  var current = repo.GetPolls();
  Html.RenderPartial("ListPolls", current);
}

MySay/Views/Polls/ListPolls.cshtml
@model IEnumerable<MySay.Models.Poll>

<table class="table table-hover">
    <tr>
        <th class="col-lg-2">
            @Html.DisplayNameFor(model => model.Description)
        </th>
      <th class="col-lg-2">
        @Html.DisplayNameFor(model => model.EndingOn)
      </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndingOn)
        </td>
    </tr>
}
</table>

MySay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="votingApp">
<head>
  <title>@ViewBag.Title</title>
  <link rel="stylesheet" href="/Content/bootstrap.min.css" />
  <link rel="stylesheet" href="~/Content/bootstrap-slate.min.css" />
  @RenderSection("Head", false)
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="navbar navbar-default">
        <div class="navbar-header">
          <ul class="nav navbar-nav">
            <li><span class="navbar-brand"><a href="/">My Say</a></span></li>
          </ul>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Popular Polls</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("Register", "Register", "Account")</li>
          </ul>
        </div>
      </div>
    </div>
    @RenderBody()
  </div>

  <script src="~/Scripts/angular.min.js"></script>
  <script src="~/app/votingApp.js"></script>
  @RenderSection("Scripts", false)
</body>
</html>